version: '3.7'

services:
 
  db:
    image: postgres:12
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: test_database
    volumes:
      - pg_data_aprs:/var/lib/postgresql/data2/
    ports:
      - 5432:5432


volumes:
  pg_data_aprs: