"""empty message

Revision ID: 659158cbe653
Revises: efe826a294eb
Create Date: 2022-04-28 14:59:45.895934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '659158cbe653'
down_revision = 'efe826a294eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
