"""empty message

Revision ID: 9ebf2a5a49ba
Revises: 8c92e0a147e0
Create Date: 2022-04-28 17:20:41.947025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ebf2a5a49ba'
down_revision = '8c92e0a147e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
